name: Auto Update Token RCTI

on:
  push:
    branches:
      - main
  schedule:
    # Berjalan otomatis setiap 3 jam sekali
    - cron: '0 */3 * * *'
  workflow_dispatch:
    # Tombol manual agar kita bisa nge-test kapan saja

jobs:
  update-m3u:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Tarik Kode dari GitHub
        uses: actions/checkout@v4

      - name: ğŸ Siapkan Mesin Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: ğŸ“¦ Install module requests
        run: pip install requests

      - name: ğŸš€ Jalankan Bot Update Token
        run: python update_rcti.py

      - name: ğŸ’¾ Simpan (Commit) Perubahan ke GitHub
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add streams/id.m3u
          # Mengecek apakah ada link yang berubah. Kalau ada, simpan!
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update token RCTI m3u8" && git push)
